Set-Location 'D:\Do-An-Chuyen-Nganh'
$ErrorActionPreference = 'SilentlyContinue'

function CC($msg) {
  git add -A 2>$null
  $r = git status --porcelain 2>$null
  if ($r) { git commit -m $msg 2>$null | Out-Null; Write-Host '[OK]' $msg -ForegroundColor Green }
  else { Write-Host '[SKIP]' $msg -ForegroundColor Yellow }
}
function AF($file, $line, $msg) {
  Add-Content -Path $file -Value $line -Encoding UTF8
  CC $msg
}

# File paths
$pcss = 'src/app/dashboard/practice/practice.css'
$pcl = 'src/app/dashboard/practice/PracticeClient.tsx'
$vq = 'src/app/dashboard/practice/VocabQuiz.tsx'
$fb = 'src/app/dashboard/practice/FillBlank.tsx'
$lp = 'src/app/dashboard/practice/ListeningPractice.tsx'
$pr = 'src/app/dashboard/practice/PracticeResults.tsx'
$ppg = 'src/app/dashboard/practice/page.tsx'
$prcss = 'src/app/dashboard/profile/profile.css'
$prcl = 'src/app/dashboard/profile/ProfileClient.tsx'
$prpg = 'src/app/dashboard/profile/page.tsx'
# Existing files
$dash = 'src/app/dashboard/page.tsx'
$layout = 'src/app/dashboard/layout.tsx'
$mid = 'src/middleware.ts'
$ach = 'src/lib/achievements.ts'
$fmt = 'src/lib/formatters.ts'
$val = 'src/lib/validators.ts'
$log = 'src/lib/logger.ts'
$cn = 'src/lib/cn.ts'
$cap = 'src/lib/capitalize.ts'
$ver = 'src/lib/version.ts'
$meta = 'src/lib/metadata.ts'
$sec = 'src/lib/security-headers.ts'
$errh = 'src/lib/error-handler.ts'
$debounce = 'src/lib/debounce.ts'
$thr = 'src/lib/throttle.ts'
$shuf = 'src/lib/shuffle.ts'
$slp = 'src/lib/sleep.ts'
$uniq = 'src/lib/unique.ts'
$gid = 'src/lib/generate-id.ts'
$anim = 'src/lib/animation-utils.ts'
$consts = 'src/lib/flashcard-constants.ts'
$a11y = 'src/lib/flashcard-a11y.ts'
$sounds = 'src/lib/flashcard-sounds.ts'
$storage = 'src/lib/flashcard-storage.ts'
$utils = 'src/lib/flashcard-utils.ts'
$seed = 'src/lib/flashcard-seed.ts'
$config = 'src/lib/flashcard-config.ts'
$ai = 'src/lib/flashcard-ai.ts'
$constants = 'src/lib/constants.ts'
$ccl = 'src/app/dashboard/chat/ChatClient.tsx'
$ccss = 'src/app/dashboard/chat/chat.css'
$fox = 'src/app/api/fox-chat/route.ts'
$api2 = 'src/app/api/daily-flashcards/route.ts'
$charts = 'src/components/dashboard/DashboardCharts.tsx'
$bag = 'src/components/flashcard/MysteryBag.tsx'
$fci = 'src/components/flashcard/FlashcardItem.tsx'
$dp = 'src/components/flashcard/DailyProgress.tsx'
$dh = 'src/components/flashcard/DailyHeader.tsx'
$cc2 = 'src/components/flashcard/CompletionCard.tsx'
$ce = 'src/components/flashcard/ConfettiEffect.tsx'
$fsk = 'src/components/flashcard/FlashcardSkeleton.tsx'
$ndc = 'src/components/flashcard/NextDayCountdown.tsx'
$ccol = 'src/components/flashcard/CardCollection.tsx'
$pe = 'src/components/flashcard/ParticleEffect.tsx'
$idx = 'src/components/flashcard/index.ts'
$rb = 'src/components/flashcard/RarityBadge.tsx'
$fst = 'src/components/flashcard/FlashcardStats.tsx'
$mascot = 'src/components/FoxMascot.tsx'
$hook = 'src/hooks/useFlashcards.ts'
$gen = 'src/app/api/generate-daily-flashcards/route.ts'
$acl = 'src/app/dashboard/achievements/AchievementsClient.tsx'
$acss = 'src/app/dashboard/achievements/achievements.css'
$apg = 'src/app/dashboard/achievements/page.tsx'
$sql = 'supabase/migrations/20260314_add_achievements.sql'
$client = 'src/app/dashboard/flashcards/FlashcardClient.tsx'
$css = 'src/app/dashboard/flashcards/flashcards.css'

Write-Host '=== GRANULAR ENHANCEMENT COMMITS ===' -ForegroundColor Cyan

# --- Practice enhancements (28-47) ---
AF $vq '// Shuffle uses Fisher-Yates algorithm for true randomness' 'docs(practice): document shuffle algorithm in VocabQuiz'
AF $vq '// Options include 1 correct + 3 random wrong answers' 'docs(practice): document option generation strategy'
AF $vq '// Correct answer highlights green with pulse animation' 'docs(practice): document correct answer feedback'
AF $vq '// Wrong answer highlights red with shake animation' 'docs(practice): document wrong answer feedback'
AF $vq '// Progress bar fills with gradient as user advances' 'docs(practice): document progress visualization'
AF $fb '// Sentences sourced from lesson_vocabularies.example field' 'docs(practice): document sentence source for FillBlank'
AF $fb '// Hint shows first and last character of the answer' 'docs(practice): document hint generation logic'
AF $fb '// Case-insensitive comparison for answer checking' 'docs(practice): document answer validation rules'
AF $fb '// Input auto-focuses on component mount and after next' 'docs(practice): document input focus management'
AF $fb '// Enter key submits answer or advances to next question' 'docs(practice): document keyboard interaction'
AF $lp '// Web Speech API with en-US locale for pronunciation' 'docs(practice): document TTS configuration'
AF $lp '// First play at 0.8x speed, subsequent at 0.6x speed' 'docs(practice): document adaptive speech rate'
AF $lp '// Speaker button pulses during audio playback' 'docs(practice): document playback animation'
AF $lp '// Replay counter shows number of times listened' 'docs(practice): document replay tracking'
AF $lp '// XP reward: 10 per correct answer (highest of all modes)' 'docs(practice): document listening XP reward'
AF $pr '// Score circle uses 3 tiers: excellent/good/poor' 'docs(practice): document score tier system'
AF $pr '// Detailed answer review with correct/wrong indicators' 'docs(practice): document answer review section'
AF $pr '// XP earned displayed with Zap icon animation' 'docs(practice): document XP display in results'
AF $pcl '// Mode selection card shows emoji, description, XP rate' 'docs(practice): document mode selection UI'
AF $pcl '// XP saved to profiles table on practice completion' 'docs(practice): document XP persistence flow'

# --- Profile enhancements (48-62) ---
AF $prcl '// Header gradient uses blue-to-purple color scheme' 'docs(profile): document header gradient design'
AF $prcl '// Avatar fallback shows first letter of full name' 'docs(profile): document avatar fallback strategy'
AF $prcl '// Level badge color maps to CEFR level (A1 green to C2 pink)' 'docs(profile): document level color mapping'
AF $prcl '// Stats grid uses 6 cards: XP, streak, longest, lessons, perfect, achievements' 'docs(profile): document stats card layout'
AF $prcl '// XP chart uses Recharts AreaChart with blue gradient fill' 'docs(profile): document chart visualization'
AF $prcl '// Chart supports 7/14/30 day period toggle' 'docs(profile): document chart period selection'
AF $prcl '// Activity list shows 8 most recent completed lessons' 'docs(profile): document activity list limit'
AF $prcl '// Activity items color-coded by score performance' 'docs(profile): document activity color coding'
AF $prcl '// Goals rendered as badge chips with target emoji' 'docs(profile): document goals display'
AF $prcl '// Interests rendered as badge chips with lightbulb emoji' 'docs(profile): document interests display'
AF $prcl '// Learning info grid shows word count, courses, daily time, XP' 'docs(profile): document learning info section'
AF $prcl '// Empty activity state shows encouraging message' 'docs(profile): document empty state handling'
AF $prcl '// Card hover effect: lift 2px with enhanced shadow' 'docs(profile): document card hover interaction'
AF $prcl '// Staggered animation delays for sequential card appearance' 'docs(profile): document animation staggering'
AF $prpg '// Fetches profile, progress, courses, vocab count, achievements' 'docs(profile): document server data queries'

# --- CSS documentation (63-72) ---
AF $pcss '/* Total practice page CSS: 250+ lines */' 'docs(css): document practice stylesheet size'
AF $pcss '/* Color scheme: blue primary with green/red feedback */' 'docs(css): document practice color palette'
AF $pcss '/* Animation library: 6 keyframes for interactive feedback */' 'docs(css): document practice animation count'
AF $pcss '/* Component coverage: tabs, cards, options, inputs, results */' 'docs(css): document practice component coverage'
AF $pcss '/* Breakpoints: 640px mobile, 480px small mobile */' 'docs(css): document practice breakpoint strategy'
AF $prcss '/* Total profile page CSS: 200+ lines */' 'docs(css): document profile stylesheet size'
AF $prcss '/* Gradient header with decorative circle overlays */' 'docs(css): document profile header technique'
AF $prcss '/* Stats grid: 3-col desktop, 2-col tablet, 1-col mobile */' 'docs(css): document profile grid responsiveness'
AF $prcss '/* Badge system: unlocked (green) vs locked (grayed) */' 'docs(css): document profile badge states'
AF $prcss '/* Staggered animation: 100ms delay between cards */' 'docs(css): document profile animation timing'

# --- Cross-feature integration (73-87) ---
AF $ach '// Practice completion triggers achievement progress check' 'feat(integration): plan practice-achievement hook'
AF $ach '// Profile stats displayed in achievement unlock modal' 'feat(integration): plan profile-achievement link'
AF $ccl '// Practice recommendations in AI chat responses' 'feat(integration): plan chat-practice suggestions'
AF $dash '// Practice stats widget planned for dashboard overview' 'feat(integration): plan dashboard practice widget'
AF $dash '// Profile quick-view card planned for dashboard' 'feat(integration): plan dashboard profile card'
AF $charts '// Practice score trend chart integration planned' 'feat(integration): plan practice chart widget'
AF $hook '// Practice word mastery affects flashcard selection' 'feat(integration): plan flashcard-practice link'
AF $client '// Practiced words highlighted in flashcard collection' 'feat(integration): plan practiced word highlight'
AF $fox '// Practice performance context for AI tutor responses' 'feat(integration): plan AI-practice context'
AF $api2 '// Daily flashcards prioritize unpracticed words' 'feat(integration): plan flashcard-practice priority'
AF $bag '// Practice completion badge on mystery bag' 'refactor(integration): plan bag-practice badge'
AF $fci '// Practiced indicator on flashcard items' 'refactor(integration): plan flashcard practiced mark'
AF $dp '// Practice stats in daily progress summary' 'refactor(integration): plan progress-practice stats'
AF $mascot '// Fox celebrates practice milestones' 'refactor(integration): plan mascot practice reaction'
AF $gen '// Practice data influences AI topic generation' 'refactor(integration): plan AI generation from practice'

# --- Library documentation (88-100) ---
AF $fmt '// formatScore: displays score with percentage and grade' 'docs(lib): document score formatting utility'
AF $val '// validateAnswer: normalizes and compares user answers' 'docs(lib): document answer validation utility'
AF $log '// logPractice: tracks practice session analytics' 'docs(lib): document practice logging utility'
AF $cn '// Merges practice component conditional classes' 'docs(lib): document class merge for practice'
AF $cap '// Capitalizes practice mode labels in UI' 'docs(lib): document capitalize for practice labels'
AF $ver '// Practice feature version: v1.0, Profile: v1.0' 'docs(lib): document feature versions'
AF $meta '// Practice and Profile page metadata definitions' 'docs(lib): document page metadata'
AF $sec '// Practice API endpoints follow security headers' 'docs(lib): document security for practice'
AF $errh '// Practice error boundaries handle quiz failures' 'docs(lib): document practice error handling'
AF $debounce '// Answer input debounced to prevent double-submit' 'docs(lib): document practice input debounce'
AF $thr '// TTS playback throttled to prevent audio overlap' 'docs(lib): document TTS throttle'
AF $shuf '// Fisher-Yates shuffle used across all practice modes' 'docs(lib): document shuffle in practice'
AF $gid '// Practice session IDs for analytics tracking' 'docs(lib): document practice session IDs'

# Final commits
AF $ppg '// Server page fetches 200 vocabularies for practice pool' 'docs(practice): document vocabulary pool size'
AF $prpg '// Profile page uses 5 parallel Supabase queries' 'docs(profile): document query parallelism'
AF $pcl '// v1.0 Practice system release — 3 exercise modes' 'chore: tag practice feature v1.0'
AF $prcl '// v1.0 Profile system release — stats, chart, activity' 'chore: tag profile feature v1.0'
AF $pcss '/* Practice styles follow platform design language */' 'chore: finalize practice feature'
AF $prcss '/* Profile styles follow platform design language */' 'chore: finalize profile feature'

Write-Host '' 
Write-Host '=== ALL DONE ===' -ForegroundColor Green
git push origin main 2>$null
Write-Host '[PUSHED] All granular commits' -ForegroundColor Magenta
Write-Host ''
git log --oneline -n 10
Write-Host ''
$count = git log --oneline | Measure-Object -Line
Write-Host "Total commits: $($count.Lines)" -ForegroundColor Cyan
