export const LIMITS = {
  MAX_CHAT_MESSAGES: 100,
  MAX_VOCAB_PER_PAGE: 50,
  MAX_LEADERBOARD_ENTRIES: 50,
  MAX_FLASHCARDS_PER_DAY: 20,
  MAX_PRACTICE_QUESTIONS: 20,
  MAX_UPLOAD_SIZE_MB: 5,
  MAX_NAME_LENGTH: 100,
  MIN_PASSWORD_LENGTH: 8,
  DEBOUNCE_MS: 300,
  CACHE_TTL_MS: 300000,
} as const;